### ISSUE TITLE
RF24 could not send radio packet in 0x65646f4e32

### ISSUE THREAD

**Issue by XxMartian** [ludiazv/node-red-contrib-nrf24#1]
could any one help?
RPi 3B+

![00](https://user-images.githubusercontent.com/5999367/53867199-4f9eef00-402e-11e9-9734-1fc3e89eda00.png)
![01](https://user-images.githubusercontent.com/5999367/53867202-50378580-402e-11e9-9b6b-701fdd1bba58.png)
![02](https://user-images.githubusercontent.com/5999367/53867203-50378580-402e-11e9-8931-81d9f8e0fa88.png)

**Comment by ludiazv** [comment]
Hi,
   Are you runing a 64bit OS?

**Comment by XxMartian** [comment]
> Hi,
> Are you runing a 64bit OS?

no，i use the official raspbian（Raspbian Stretch with desktop and recommended software 20181113）
I want transfer multicast，so donot need the ACK。

the detail print below，
![image](https://user-images.githubusercontent.com/5999367/53928188-2df04700-40c4-11e9-9183-759e0598db52.png)
![image](https://user-images.githubusercontent.com/5999367/53928203-3779af00-40c4-11e9-8a29-776e425debcc.png)

**Comment by ludiazv** [comment]
Hi,
   ACK is enabled in all pipes. As your receiver is in not sending the ACK the ACK is not received after retries. The register is this

Name
Bit
Reset Value
Type	Description
Reserved	7	0	R/W	Only '0' allowed
Reserved	6	0	R/W	Only '0' allowed
ENAA_P5	5	1	R/W	Enable auto acknowledgement data pipe 5
ENAA_P4	4	1	R/W	Enable auto acknowledgement data pipe 4
ENAA_P3	3	1	R/W	Enable auto acknowledgement data pipe 3
ENAA_P2	2	1	R/W	Enable auto acknowledgement data pipe 2
ENAA_P1	1	1	R/W	Enable auto acknowledgement data pipe 1
ENAA_P0	0	1	R/W	Enable auto acknowledgement data pipe 0

For deactivating it you need to edit the Outputnode and uncheck the ACK flag.

**Comment by ludiazv** [comment]
Ops! I just noticed that the version that is published is an old one that dot not support deactivating ACK. I will update the repository during the weekend.

**Comment by XxMartian** [comment]
> Ops! I just noticed that the version that is published is an old one that dot not support deactivating ACK. I will update the repository during the weekend.

thanks

**Comment by ludiazv** [comment]
@XxMartian check the master branch. The new version is published now. It should work now without ACK.

**Comment by ludiazv** [comment]
closed due inactivity. Please reopen if needed.
