### ISSUE TITLE
Default configuration does not work

### ISSUE THREAD

**Issue by Zykino** [ludiazv/node-red-contrib-nrf24#2]
Default wiring provided by https://github.com/ludiazv/node-nrf24 and default conf of this module result in this line appearing every 2s. `RF24 HARDWARE FAIL: Radio not responding, verify pin connections, wiring, etc.`

node red web interface is not responding. I don't know how to fix this (start node red without it's flows)

Raspi 3B+
Raspbian Stretch Lite from April 2019 (updated/upgraded).

**Comment by ludiazv** [comment]
Hi,
  This error is reported directly buy the RF24 library. This is typcally due to wiring problems or lack of power in the module. You need to adapt the wiring to your configuration if this is not the case. I will need some detail to track the issue.

**Comment by Zykino** [comment]
Hi,  
As said in #3, I followed the wiring instructions of the [base package](https://github.com/ludiazv/node-nrf24). But the instructions point toward setting the CE parameter to 22, not 25 like the current default of this package (1st problem).

2nd problem: Once a bad config is deployed, node-red interface is unusable, web interface and `node-red-stop` doesn't work. I don't know how to start node red web interface without starting the deployed flow. So a user need to go in the red node config file and fix the config by hand. I'm sure it's possible to get the error and stop trying to send the message. Or do something so node-red does not freeze.

**Comment by ludiazv** [comment]
Hi,
1st. the CE pin is selectable by the user according to your wiring you can use any GPIO. The documentation uses 22 and 25 just as examples. I typically use 22 & 24 for CE lines but this is because I use a custom board that uses this two pins but you can change it. This is why they are mandatory to create the radio configuration node or in the constructor in the base library. 

2nd: I will do some tests to avoid this problem. I hope to have some answers soon.

**Comment by ludiazv** [comment]
Hi,
  I discover the problem for the 2nd point here. I have to test it but i think I can release a new version in the comming days to manage faliure situations. The problem is on how the base library is compiled.

**Comment by ludiazv** [comment]
Hi @Zykino ,
   I included in the master branch a test during radio init to check if wiring is OK. Now it do not hang node-red and report an error. If interested check it out.
  This closes the 2nd issue.  I added a new feature to implement auto recovery of hardware failure transparent to the user. This is experemintal but can be enabled in the config node checking the flag to activate auto recovery.

**Comment by oliverhruby** [comment]
Hi, will there be a new npm some time soon for the fixes? Version 0.0.2 is not showing any configuration node (just a textbox with no way to expand to configure it) so it's not possible to use it. I'm not sure if this is related to the issues mentioned in this thread.

**Comment by ludiazv** [comment]
I need to update the docs and a final test. I will try during the weekend.

**Comment by oliverhruby** [comment]
Sorry this time it was my problem :) I didn't check the node-red logs, I
had issues with RF24 package, after fixing that the configuration node was
showing ok.

Thanks for this library, you're doing a great job. One minor suggestion -
think about putting a Donate icon on your github readme, people can send
you something if they find your library useful.

Oliver


Dňa po, 17. jún 2019 10:24 AM ludiazv <notifications@github.com> napísal(a):

**Comment by ludiazv** [comment]
Great. I will do a test while I finish the documentation. Thanks for the feedback.

As regards "Donate button". Frankly I do not know how to do it. any suggestions?
